# Generated by Django 4.2.23 on 2025-07-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_business_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorApplication',
        ),
    ]
